mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps= {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create own manager
class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager,
                     self).get_queryset()\
                     .filter(status='published')
                     

# Create your models here.
class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        )
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICE,
                              default='draft')
    
    class Meta:
        ordering = ('-publish',)
        
    def __str__(self) -> str:
        return self.title
    
    objects = models.Manager()      # default Manager
    published = PublishManager()    # non deafault Manager
    
    def get_absolute_url(self):
        return reverse("blog:post_detail",
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])
        
    tags = TaggableManager()
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
        
    def __str__(self) -> str:
        return f'Komentarz dodany przez { self.name } dla posta { self.post }'
    
    

mysite/blog/forms.py
from django import forms  

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", 'email', 'body',)


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.contrib.postgres.search import TrigramSimilarity
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.

### definition post list ###
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    
    paginator = Paginator(object_list, 3)   # 3 posts on page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        
    return render(request,
                  'blog/post/list.html',
                  { 'page': page,
                    'posts': posts,
                    'tag': tag })

### class post list ###
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'
    
    
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,  slug=post,
                                    status = 'published',
                                    publish__year = year,
                                    publish__month=month,
                                    publish__day=day)
    
    comments = post.comments.filter(active=True)
    new_comment_sent = False
    
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            new_comment_sent = True
    else:
        comment_form = CommentForm()
        
    post_list_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_list_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  { 'post': post,
                    'comments': comments,
                    'comment_form': comment_form,
                    'new_comment_sent': new_comment_sent,
                     'similar_posts': similar_posts })

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{ cd['name'] } ({ cd['email'] }) zachęca do przeczytania \"{ post.title }\""
            message = f"Przeczytaj post \"{ post.title }\" na stronie { post_url }\n\nKomentarz dodany przez { cd['name'] }: { cd['comments'] }"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})
    
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            
            """normal serch"""
            # search_vector = SearchVector('title', 'body')
            
            """serch with weight"""
            # search_vector = SearchVector('title', weight='A') +\
            #                 SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            
            """search with trigram"""
            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query)
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results })

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>

<body>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>

    <div id="sidebar">
        <h2>Mój blog</h2>
        <p>To jest mój blog. Dotychczas opublikowałe {% total_posts %} postów.</p>

        <p>
            <a href="{% url 'blog:post_feed' %}">Subkrybuj kanał RSS</a>
        </p>

        <h3>Najnowsze posty</h3>
        {% show_latest_posts 3 %}

        <h3>Najczęściej komentowane posty</h3>
        {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
    </div>
</body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class='date'>
        Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href={% url 'blog:post_share' post.id %}>
            Udostępnij post
        </a>
    </p>

    <h2>Podobne posty</h2>
    {% for post in similar_posts %}
        <p>
            <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
        </p>
    {% empty %}
        Nie ma podobnych postów.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p> Nie ma jeszcze komentarzy.</p>
    {% endfor %}

    {% if new_comment_sent %}
        <h2>Twój komentarz został dodany</h2>
    {% else %}
        <h2>Dodaj nowy komentarz</h2>
        <form method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type='submit' value="Dodaj komentarz"></p>
        </form>
    {% endif %}

{% endblock content %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Mój blog{% endblock title %}

{% block content %}
    <h1>Mój blog</h1>
    {% if tag %}
        <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            <p class='tags'>
                Tagi:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </h2>
        <p class='date'>
            Opublikowano {{ post.publish }} przez {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords:30 }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}
{% endblock content %}

mysite/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Szukaj{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posty zawierające "{{ query }}"</h1>
        <h3>Znaleziono {{ total_results }} wynik {{ total_results|pluralize:'i' }}</h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatechars_html:5}}
        {% empty %}
            <p>Brak wyników dla podanego zapytania</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Szukaj ponownie</a></p>
    {% else %}
        <h1>Szukaj postów</h1>
        <form method='get'>
            {{ form.as_p }}
            <input type="submit" value='Szukaj'>
        </form>
    {% endif %}
{% endblock content %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Udostępnij post{% endblock title %}

{% block content %}
    {% if sent %}
        <h1>Wiadomość email została wysłana</h1>
        <p>
            Wysłanie posta "{{ post.title }}" do {{ form.clear_data.to }} zakończyło się sukcesem.
        </p>
    {% else %}
        <h1>Udostępnij "{{ post.title }}" prze e-mail</h1>
        <form action="." method='post'>
            {% csrf_token %}
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="Wyślij wiadomość e-mail">
        </form>
    {% endif %}
{% endblock content %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step=links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}.
        </span>
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">Następna</a>   
            {% endif %}
    </span>
</div>